variables:
  CONTAINER_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:
  image: docker:stable
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CONTAINER_REGISTRY
  services:
  - docker:dind
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest

ergodox:
  image: $CONTAINER_IMAGE:latest
  stage: build
  script:
    - make ergodox_ez:tj-anderson
  artifacts:
    paths:
      - ./*.hex
